DH_Blog/Controllers/BlogPostsController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DH_Blog.Helpers;
using DH_Blog.Models;
using PagedList;


namespace DH_Blog.Controllers
{
    [RequireHttps]
    public class BlogPostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BlogPosts
        [Authorize(Roles = "Admin")]
        public ActionResult Index(int? page, string searchStr)
        {
            ViewBag.Search = searchStr;
            var blogList = IndexSearchClass.IndexSearch(searchStr);
            int pageSize = 5; // the number of posts you want to display per page
            int pageNumber = (page ?? 1);
            return View(blogList.ToPagedList(pageNumber, pageSize));
        }

        [Authorize(Roles = "Admin")]
        public ActionResult UnPubIndex(int? page)
        {
            int pageSize = 5; // the number of posts you want to display per page
            int pageNumber = (page ?? 1);

            var unpubPosts = db.BlogPosts.Where(b => !b.Published).OrderByDescending(c => c.Created);
            return View("Index", unpubPosts.ToPagedList(pageNumber, pageSize));
        }


        // GET: BlogPosts/Details/5
        public ActionResult Details(string Slug)
        {
            if (String.IsNullOrWhiteSpace(Slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.FirstOrDefault(p => p.Slug == Slug);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // GET: BlogPosts/Create
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Abstract,BlogPostBody,Published")] BlogPost blogPost, HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                var Slug = StringUtilities.URLFriendly(blogPost.Title);
                if (string.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid title");
                    return View(blogPost);
                }
                if(db.BlogPosts.Any(p => p.Slug == Slug))
                {
                    ModelState.AddModelError("Title", "The title must be unique");
                    return View(blogPost);
                }
                if (ImageUploadValidator.IsWebFriendlyImage(Image))
                {
                    var fileName = Path.GetFileName(Image.FileName);
                    fileName = Path.GetFileNameWithoutExtension(fileName) + "_" + DateTime.Now.Ticks + Path.GetExtension(fileName);
                    Image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.ImagePath = "/Uploads/" + fileName;
                }

                blogPost.Slug = Slug;
                blogPost.Created = DateTime.Now;
                db.BlogPosts.Add(blogPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogPost);
        }

        //GET: BlogPosts/Edit/5
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Edit(string Slug)
        {
            if (String.IsNullOrWhiteSpace(Slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.FirstOrDefault(p => p.Slug == Slug);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id, Title, Abstract, BlogPostBody,Published,Created,Slug, ImagePath")] BlogPost blogPost, HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                var newSlug = StringUtilities.URLFriendly(blogPost.Title);
                if(newSlug != blogPost.Slug)
                {
                    if (string.IsNullOrWhiteSpace(newSlug))
                    {
                        ModelState.AddModelError("Title", "Invalid title");
                        return View(blogPost);
                    }
                    if (db.BlogPosts.Any(p => p.Slug == newSlug))
                    {
                        ModelState.AddModelError("Title", "The title must be unique");
                        return View(blogPost);
                    }
                    blogPost.Slug = newSlug;
                }
                if (ImageUploadValidator.IsWebFriendlyImage(Image))
                {
                    var fileName = Path.GetFileName(Image.FileName);
                    Image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.ImagePath = "/Uploads/" + fileName;
                }

                blogPost.Updated = DateTime.Now;
                db.Entry(blogPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.BlogPosts.Find(id);
            db.BlogPosts.Remove(blogPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DH_Blog/Controllers/HomeController.cs
using DH_Blog.Helpers;
using DH_Blog.Models;
using PagedList;
using System;
using System.Configuration;
using System.Diagnostics;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DH_Blog.Controllers
{   
    [RequireHttps]
    public class HomeController : Controller
    {
        public ActionResult Contact()
        {
            EmailModel model = new EmailModel();
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Contact(EmailModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await EmailHelper.ComposeEmailAsync(model);
                    TempData["sent"] = "Success";
                    return RedirectToAction("Contact");
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(ex.Message);
                    await Task.FromResult(0);
                }
            }
            return View(model);
        }


        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index(int? page, string searchStr)
        {
            ViewBag.Search = searchStr;
            var blogList = IndexSearchClass.IndexSearch(searchStr);
            int pageSize = 3; // the number of posts you want to display per page
            int pageNumber = (page ?? 1);
            return View(blogList.ToPagedList(pageNumber, pageSize));
        }


        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

    }
}

DH_Blog/Views/Home/About.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        #about {
            width: 100%;
            height: auto;
            background: #fff;
            padding-top: 90px;
            padding-bottom:45px;
        }
        #about .div-img-bg {
            padding-bottom: 30px;
            border: 20px solid #b8a07e;
        }
        #about .div-img-bg .about-img img {
            width: 100%;
            box-shadow: 0px 0px 85px 0px rgba(0, 0, 0, 0.14);
            margin-top: -60px;
            margin-left: 40px;
            height: 400px;
            object-fit: cover;
        }
        #about .about-descr .p-heading {
            font-family: 'Playfair Display', serif;
            font-size: 28px;
            text-align: left;
        }
        #about .about-descr .separator {
            max-width: 80%;
            margin-bottom: 0;
            text-align: left;
        }
    </style>
</head>
<body>
    <!-- start section about us -->
    <div class="container" id="about">
        <div class="row justify-content-between">

            <div class="col-lg-4 ">
                <div class="div-img-bg">
                    <div class="about-img">
                        <img src="~/IMGs/me.jpg" class="img-responsive" alt="me" />
                    </div>
                </div>
            </div>

            <div class="col-lg-7">
                <div class="about-descr">

                    <p class="p-heading">I'm a North Carolina based web developer who loves clean, simple & unique design. I also enjoy digital artistry, ui/ux creation, & logo design. </p>
                    <p class="separator">Raised with computers, I found a passion for all things digital at an early age. Over the years I've delved into all the different aspects of coding, digital art, & web production.</p>

                </div>
            </div>
        </div>
    </div>

    @section scripts{
        @*script to change the masthead stuff*@
        <script>
            $(document).ready(function () {
                // Set background image of a div on load
                var imageUrl = "/IMGs/about-bg.jpg";
                $(".masthead").css("background-image", "url(" + imageUrl + ")");
                $('#topText').text("About");
                $('#subText').text("Let's talk about me");
            });
        </script>
    }

</body>

</html>

DH_Blog/Views/Home/Contact.cshtml
@model DH_Blog.Models.EmailModel

<!DOCTYPE html>
<html lang="en">

<body>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div id="sendmessage" class="h3"><p>Your message has been sent. Thank you!</p></div>
                <p style="padding-left:30px">Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                <div class="col-lg">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group contact-block1">
                                    <input type="text" name="fromname" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars">
                                    <div class="validation"></div>
                                </div>
                            </div>

                            <div class="col-lg-6">
                                <div class="form-group">
                                    <input type="email" class="form-control" name="fromemail" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email">
                                    <div class="validation"></div>
                                </div>
                            </div>

                            <div class="col-lg-12">
                                <div class="form-group">
                                    <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject">
                                    <div class="validation"></div>
                                </div>
                            </div>

                            <div class="col-lg-12">
                                <div class="form-group">
                                    <textarea class="form-control" name="Body" rows="12" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                                    <div class="validation"></div>
                                </div>
                            </div>

                            <div class="col-lg-12">
                                <input type="submit" class="btn btn-block allButtons" value="Send message">
                            </div>

                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

    <hr>

    @section scripts
    {
        @*script to change the masthead stuff*@
        <script>
        $(document).ready(function () {
            // Set background image of a div on load
            var imageUrl = "/IMGs/contact-bg.jpg";
            $(".masthead").css("background-image", "url(" + imageUrl + ")");
            $('#topText').text("Contact");
            $('#subText').text("See something you like? Reach me here");
        });
        </script>
        <script>
            if ('@TempData["sent"]' == 'Success') {
                $('#sendmessage').show();
            }
            else {
            $('#sendmessage').hide();
            }
        </script>
    }

</body>

</html>

DH_Blog/Views/Home/Index.cshtml
@using DH_Blog.Models
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<BlogPost>

<link href="~/Content/PagedList.css" rel="stylesheet" />

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <div class="col d-flex justify-content-end" style="padding-bottom: 15px">
                Search the Blogs for key words.
            </div>
            <div class="col d-flex justify-content-end">
                @using (Html.BeginForm("Index", "Home", FormMethod.Get, htmlAttributes: new { @class = "form" }))
                {

                    <div class="controls controls-row search-row">
                        <input id="searchStr" name="searchStr" class="input-block-level" type="text"
                               placeholder="Search" style="padding:5px">
                <button id="searchstr" name="searchstr" class="btn allButtons" type="submit">
                    <i>Search</i>
                </button>
                    </div>
                }
            </div>
            <hr />
            @foreach (var blogPost in Model.OrderByDescending(b => b.Created))
            {
                <div class="post-preview">
                    <div class="row">
                        @if (blogPost.ImagePath != null)
                        {
                            <div class="col-3 d-flex justify-content-end">
                                <img style="width:115px; height:115px" src="@blogPost.ImagePath " alt="" />
                            </div>
                        }
                        <div class="col-9">
                            <a href=@Url.Action("Details","BlogPosts",new {slug = blogPost.Slug})>
                                <h2 class="post-title">
                                    @blogPost.Title
                                </h2>
                                <h4 class="post-subtitle">
                                    @blogPost.Abstract
                                </h4>
                            </a>
                        </div>
                    </div>
                    <p class="post-meta" style="margin-left:50px">
                        Posted by
                        @Html.ActionLink("Daniel Hebbard", "About", "Home")
                        on @blogPost.Created.ToString("MMM dd, yyyy")
                    </p>
                </div>
                <hr>
            }
            <div class="col">
                <div class="col d-flex justify-content-end">
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                </div>
                <div class="col d-flex justify-content-end">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, searchStr = ViewBag.Search }))
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts
{

}